apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - basicauth-secret.yaml
  - basicauth-middleware.yaml
  - helmrepository.yaml
  - helmrelease-backend.yaml
  - helmrelease-collector.yaml