apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crds/cert-manager.crds.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - sealed-digitalocean-token-secret.yaml
  - issuer-letsencrypt-prod.yaml
  - cert-prod-masterloft-marcel-lambacher-de.yaml